### ISSUE TITLE
Grammar error in German search box

### ISSUE THREAD

**Issue by WebSnke** [Homebrew/brew.sh#950]
The search window on this page on the German page looks like this:

![image](https://user-images.githubusercontent.com/94064167/235312712-a10e841a-8c21-452f-ab64-06a3fae89110.png)

"Suchen Homebrew" is grammatically incorrect though. 
I therefore suggest removing "Homebrew" in that string, therefore in [base.html](https://github.com/Homebrew/brew.sh/blob/aed21cd7f600b471352a60fca570ac4a15e737d0/_layouts/base.html#L136).

I would love to be assigned this issue and resolve it.

**Comment by MikeMcQuaid** [comment]
@WebSnke sounds good, would love a PR but one that doesn't change the wording in English.

**Comment by WebSnke** [comment]
> @WebSnke sounds good, would love a PR but one that doesn't change the wording in English.

Got it. I will try my best.

**Comment by WebSnke** [comment]
My idea is to define the entire search string instead of just the literal translation for "search". Does that sound go to you, @MikeMcQuaid?

**Comment by MikeMcQuaid** [comment]
@WebSnke Sounds perfect and best practise for translations generally 👍🏻

**Comment by MikeMcQuaid** [comment]
Will review a PR when you get the chance @WebSnke!

**Comment by WebSnke** [comment]
> Will review a PR when you get the chance @WebSnke!

It's not a matter of time. I just can't run the website locally to test my changes...

**Comment by MikeMcQuaid** [comment]
@WebSnke What's the output of the instructions in https://github.com/Homebrew/brew.sh#github-pull-request?

**Comment by WebSnke** [comment]
> @WebSnke What's the output of the instructions in [Homebrew/brew.sh#github-pull-request](https://github.com/Homebrew/brew.sh#github-pull-request)?

Here you go:
```bash
╭─ ~/Downloads/brew.sh  master ─────────────────────────────────────────── ✔ ─╮
╰─ bundle install                                                            ─╯
bash: bundle: command not found...
Install package 'rubygem-bundler' to provide command 'bundle'? [N/y] y


 * Waiting in queue... 
 * Loading list of packages.... 
The following packages have to be installed:
 ruby-3.2.2-180.fc38.x86_64	An interpreter of object-oriented scripting language
 ruby-default-gems-3.2.2-180.fc38.noarch	Default gems which are part of Ruby StdLib
 ruby-libs-3.2.2-180.fc38.x86_64	Libraries necessary to run Ruby
 rubygem-bigdecimal-3.1.3-180.fc38.x86_64	BigDecimal provides arbitrary-precision floating point decimal arithmetic
 rubygem-bundler-2.4.10-180.fc38.noarch	Library and utilities to manage a Ruby application's gem dependencies
 rubygem-io-console-0.6.0-180.fc38.x86_64	IO/Console is a simple console utilizing library
 rubygem-json-2.6.3-202.fc38.x86_64	A JSON implementation in Ruby
 rubygem-psych-5.0.1-180.fc38.x86_64	A libyaml wrapper for Ruby
 rubygem-rdoc-6.5.0-180.fc38.noarch	A tool to generate HTML and command-line documentation for Ruby projects
 rubygems-3.4.10-180.fc38.noarch	The Ruby standard for packaging ruby libraries
 rubypick-1.1.1-18.fc38.noarch	Stub to allow choosing Ruby runtime
Proceed with changes? [N/y] y


 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Fetching rake 13.0.6

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rake-13.0.6.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rake-13.0.6.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rake-13.0.6.gem`. It is likely that you need to grant write permissions for that path.

Fetching Ascii85 1.1.0
Fetching concurrent-ruby 1.2.2
Fetching public_suffix 4.0.7
Fetching minitest 5.18.0

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/Ascii85-1.1.0.gem`. It is likely that you need to grant write permissions for that path.


Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/Ascii85-1.1.0.gem`. It is likely that you need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/public_suffix-4.0.7.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/minitest-5.18.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/Ascii85-1.1.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/minitest-5.18.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/concurrent-ruby-1.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/public_suffix-4.0.7.gem`. It is likely that you need to grant write permissions for that path.

Fetching afm 0.2.2

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/minitest-5.18.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/public_suffix-4.0.7.gem`. It is likely that you need to grant write permissions for that path.

Fetching fiber-local 1.0.0

Fetching io-event 1.2.2

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/concurrent-ruby-1.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/afm-0.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/fiber-local-1.0.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/afm-0.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/fiber-local-1.0.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/afm-0.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/fiber-local-1.0.0.gem`. It is likely that you need to grant write permissions for that path.


Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/io-event-1.2.2.gem`. It is likely that you need to grant write permissions for that path.
Fetching timers 4.3.5


Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/concurrent-ruby-1.2.2.gem`. It is likely that you need to grant write permissions for that path.
Using bundler 2.4.10
Fetching coffee-script-source 1.11.1

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/io-event-1.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/io-event-1.2.2.gem`. It is likely that you need to grant write permissions for that path.

Fetching execjs 2.8.1


Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/timers-4.3.5.gem`. It is likely that you need to grant write permissions for that path.
Fetching colorator 1.1.0

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/timers-4.3.5.gem`. It is likely that you need to grant write permissions for that path.


Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/coffee-script-source-1.11.1.gem`. It is likely that you need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/timers-4.3.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/execjs-2.8.1.gem`. It is likely that you need to grant write permissions for that path.


Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/coffee-script-source-1.11.1.gem`. It is likely that you need to grant write permissions for that path.
Fetching commonmarker 0.23.9

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/execjs-2.8.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/colorator-1.1.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/coffee-script-source-1.11.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/colorator-1.1.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/execjs-2.8.1.gem`. It is likely that you need to grant write permissions for that path.

Fetching unf_ext 0.0.8.2

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/colorator-1.1.0.gem`. It is likely that you need to grant write permissions for that path.

Fetching eventmachine 1.2.7

Fetching http_parser.rb 0.8.0

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/commonmarker-0.23.9.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/commonmarker-0.23.9.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/commonmarker-0.23.9.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/eventmachine-1.2.7.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/http_parser.rb-0.8.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/unf_ext-0.0.8.2.gem`. It is likely that you need to grant write permissions for that path.

Fetching ffi 1.15.5

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/http_parser.rb-0.8.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/eventmachine-1.2.7.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/http_parser.rb-0.8.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/unf_ext-0.0.8.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/eventmachine-1.2.7.gem`. It is likely that you need to grant write permissions for that path.

Fetching faraday-net_http 3.0.2

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/unf_ext-0.0.8.2.gem`. It is likely that you need to grant write permissions for that path.

Using ruby2_keywords 0.0.5
Fetching forwardable-extended 2.6.0

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/faraday-net_http-3.0.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/faraday-net_http-3.0.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/faraday-net_http-3.0.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/forwardable-extended-2.6.0.gem`. It is likely that you need to grant write permissions for that path.

Fetching gemoji 3.0.1

Fetching rb-fsevent 0.11.2

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ffi-1.15.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/forwardable-extended-2.6.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/forwardable-extended-2.6.0.gem`. It is likely that you need to grant write permissions for that path.

Fetching rexml 3.2.5

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/gemoji-3.0.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rb-fsevent-0.11.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/gemoji-3.0.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/gemoji-3.0.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rb-fsevent-0.11.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ffi-1.15.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rexml-3.2.5.gem`. It is likely that you need to grant write permissions for that path.


Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rb-fsevent-0.11.2.gem`. It is likely that you need to grant write permissions for that path.
Fetching liquid 4.0.4

Fetching mercenary 0.3.6

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rexml-3.2.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rexml-3.2.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ffi-1.15.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/liquid-4.0.4.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/mercenary-0.3.6.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/liquid-4.0.4.gem`. It is likely that you need to grant write permissions for that path.

Fetching rouge 3.26.0

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/mercenary-0.3.6.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/liquid-4.0.4.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/mercenary-0.3.6.gem`. It is likely that you need to grant write permissions for that path.

Fetching safe_yaml 1.0.5


Using racc 1.6.2
Fetching jekyll-paginate 1.1.0
Fetching rubyzip 2.3.2

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/safe_yaml-1.0.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/jekyll-paginate-1.1.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/safe_yaml-1.0.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rubyzip-2.3.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/jekyll-paginate-1.1.0.gem`. It is likely that you need to grant write permissions for that path.


Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rouge-3.26.0.gem`. It is likely that you need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/safe_yaml-1.0.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/jekyll-paginate-1.1.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rubyzip-2.3.2.gem`. It is likely that you need to grant write permissions for that path.

Fetching jekyll-swiss 1.0.0

Fetching unicode-display_width 1.8.0

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rubyzip-2.3.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rouge-3.26.0.gem`. It is likely that you need to grant write permissions for that path.

Fetching hashery 2.1.2

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/jekyll-swiss-1.0.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/unicode-display_width-1.8.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/jekyll-swiss-1.0.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/unicode-display_width-1.8.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rouge-3.26.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/jekyll-swiss-1.0.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/unicode-display_width-1.8.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/hashery-2.1.2.gem`. It is likely that you need to grant write permissions for that path.

Fetching ruby-rc4 0.1.5

Fetching ttfunk 1.7.0

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/hashery-2.1.2.gem`. It is likely that you need to grant write permissions for that path.


Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/hashery-2.1.2.gem`. It is likely that you need to grant write permissions for that path.
Fetching rainbow 3.1.1

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ruby-rc4-0.1.5.gem`. It is likely that you need to grant write permissions for that path.

Fetching yell 2.2.2

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ruby-rc4-0.1.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ruby-rc4-0.1.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ttfunk-1.7.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rainbow-3.1.1.gem`. It is likely that you need to grant write permissions for that path.

Fetching zeitwerk 2.6.8

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ttfunk-1.7.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/yell-2.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rainbow-3.1.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/yell-2.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ttfunk-1.7.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rainbow-3.1.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/yell-2.2.2.gem`. It is likely that you need to grant write permissions for that path.

Fetching webrick 1.8.1



Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/zeitwerk-2.6.8.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/zeitwerk-2.6.8.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/zeitwerk-2.6.8.gem`. It is likely that you need to grant write permissions for that path.


Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/webrick-1.8.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/webrick-1.8.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/webrick-1.8.1.gem`. It is likely that you need to grant write permissions for that path.

Bundler::PermissionError: There was an error while trying to write to
`/usr/share/gems/cache/rake-13.0.6.gem`. It is likely that you need to grant
write permissions for that path.
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/shared_helpers.rb:105:in
`rescue in filesystem_access'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/shared_helpers.rb:102:in
`filesystem_access'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/rubygems_integration.rb:483:in
`block in download_gem'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/retry.rb:40:in `run'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/retry.rb:30:in `attempt'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/rubygems_integration.rb:474:in
`download_gem'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/source/rubygems.rb:484:in
`download_gem'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/source/rubygems.rb:446:in
`fetch_gem'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/source/rubygems.rb:430:in
`fetch_gem_if_possible'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/source/rubygems.rb:158:in
`install'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer/parallel_installer.rb:156:in
`do_install'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer/parallel_installer.rb:84:in
`call'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer/parallel_installer.rb:67:in
`call'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer.rb:244:in
`install_in_parallel'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer.rb:201:in `install'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer.rb:89:in `block in
run'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/process_lock.rb:19:in `rescue
in lock'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/process_lock.rb:15:in `lock'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer.rb:71:in `run'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/installer.rb:23:in `install'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/cli/install.rb:62:in `run'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/cli.rb:261:in `block in
install'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/settings.rb:131:in `temporary'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/cli.rb:260:in `install'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in
`run'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in
`invoke_command'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in
`dispatch'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in
`start'
  /usr/share/gems/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
/usr/share/gems/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top
(required)>'
/usr/share/gems/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in
`with_friendly_errors'
  /usr/share/gems/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
  /usr/bin/bundle:25:in `load'
  /usr/bin/bundle:25:in `<main>'

An error occurred while installing rake (13.0.6), and Bundler cannot
continue.

In Gemfile:
  rake

```

**Comment by MikeMcQuaid** [comment]
@WebSnke I think this is an issue with your Linux distro, I'm afraid I have no idea why `bundle install` is attempting to install things into a random location like this, sorry, and I cannot help with debugging.
