### ISSUE TITLE
Set up brew.sh locally

### ISSUE THREAD

**Issue by WebSnke** [Homebrew/brew.sh#951]
I just tried to set up brew.sh on localhost by following the instructions on the README file of this project.

Unfortunately, I got a few errors even though I followed the instructions:
```bash
[websnke@fedora Downloads]$ git clone https://github.com/Homebrew/brew.sh.git
Cloning into 'brew.sh'...
remote: Enumerating objects: 6224, done.
remote: Counting objects: 100% (358/358), done.
remote: Compressing objects: 100% (215/215), done.
remote: Total 6224 (delta 130), reused 321 (delta 119), pack-reused 5866
Receiving objects: 100% (6224/6224), 8.34 MiB | 7.08 MiB/s, done.
Resolving deltas: 100% (3593/3593), done.
[websnke@fedora Downloads]$ history -c
[websnke@fedora Downloads]$ ls
brew.sh
[websnke@fedora Downloads]$ cd brew.sh
[websnke@fedora brew.sh]$ ls
analytics        index_az.html  index_fi.html  index_ku.html     index_sr.html     _posts
analytics-linux  index_be.html  index_fr.html  index_lb.html     index_sv.html     Rakefile
assets           index_bg.html  index_gl.html  index_nb.html     index_th.html     README.md
blog             index_ca.html  index_he.html  index_nl.html     index_tr.html     robots.txt
CNAME            index_cs.html  index_hi.html  index_nn.html     index_uk.html     _sass
_config.yml      index_da.html  index.html     index_pl.html     index_vi.html     security.txt
_data            index_de.html  index_id.html  index_pt-br.html  index_zh-cn.html
Gemfile          index_el.html  index_it.html  index_pt.html     index_zh-tw.html
_includes        index_es.html  index_ja.html  index_ro.html     _layouts
index_ar.html    index_fa.html  index_ko.html  index_ru.html     LICENSE.txt
[websnke@fedora brew.sh]$ jekyll serve
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/resolver.rb:290:in `raise_not_found!': Could not find gem 'github-pages' in locally installed gems. (Bundler::GemNotFound)
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/resolver.rb:343:in `block in prepare_dependencies'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/resolver.rb:328:in `each'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/resolver.rb:328:in `map'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/resolver.rb:328:in `prepare_dependencies'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/resolver.rb:53:in `setup_solver'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/resolver.rb:28:in `start'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/definition.rb:554:in `start_resolution'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/definition.rb:289:in `resolve'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/definition.rb:507:in `materialize'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/definition.rb:197:in `specs'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/definition.rb:254:in `specs_for'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/runtime.rb:18:in `setup'
	from /home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler.rb:171:in `setup'
	from /usr/share/gems/gems/jekyll-4.3.2/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /usr/share/gems/gems/jekyll-4.3.2/exe/jekyll:11:in `<top (required)>'
	from /home/websnke/bin/jekyll:25:in `load'
	from /home/websnke/bin/jekyll:25:in `<main>'
[websnke@fedora brew.sh]$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Fetching rake 13.0.6

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rake-13.0.6.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rake-13.0.6.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/rake-13.0.6.gem`. It is likely that you need to grant write permissions for that path.

Fetching Ascii85 1.1.0
Using minitest 5.18.0
Fetching afm 0.2.2
Using concurrent-ruby 1.2.2
Using public_suffix 4.0.7
Fetching fiber-local 1.0.0
Fetching io-event 1.1.7

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/Ascii85-1.1.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/afm-0.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/fiber-local-1.0.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/Ascii85-1.1.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/io-event-1.1.7.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/afm-0.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/fiber-local-1.0.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/Ascii85-1.1.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/io-event-1.1.7.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/afm-0.2.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/fiber-local-1.0.0.gem`. It is likely that you need to grant write permissions for that path.

Fetching timers 4.3.5

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/io-event-1.1.7.gem`. It is likely that you need to grant write permissions for that path.


Using bundler 2.4.12
Fetching coffee-script-source 1.11.1
Fetching execjs 2.8.1

Using colorator 1.1.0
Fetching commonmarker 0.23.9

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/timers-4.3.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/execjs-2.8.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/timers-4.3.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/coffee-script-source-1.11.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/timers-4.3.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/execjs-2.8.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/coffee-script-source-1.11.1.gem`. It is likely that you need to grant write permissions for that path.

Fetching unf_ext 0.0.8.2

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/commonmarker-0.23.9.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/execjs-2.8.1.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/coffee-script-source-1.11.1.gem`. It is likely that you need to grant write permissions for that path.


Using eventmachine 1.2.7
Using ffi 1.15.5
Using faraday-net_http 3.0.2
Using ruby2_keywords 0.0.5
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using rb-fsevent 0.11.2
Using rexml 3.2.5
Using liquid 4.0.4
Using mercenary 0.3.6

Using rouge 3.26.0
Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/commonmarker-0.23.9.gem`. It is likely that you need to grant write permissions for that path.
Using safe_yaml 1.0.5
Fetching racc 1.6.2

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/commonmarker-0.23.9.gem`. It is likely that you need to grant write permissions for that path.
Installing http_parser.rb 0.8.0 with native extensions
Using jekyll-paginate 1.1.0
Using rubyzip 2.3.2
Using jekyll-swiss 1.0.0
Using unicode-display_width 1.8.0
Fetching hashery 2.1.2

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/unf_ext-0.0.8.2.gem`. It is likely that you need to grant write permissions for that path.

Fetching ruby-rc4 0.1.5


Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/racc-1.6.2.gem`. It is likely that you need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/unf_ext-0.0.8.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/hashery-2.1.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ruby-rc4-0.1.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/racc-1.6.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/hashery-2.1.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ruby-rc4-0.1.5.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/unf_ext-0.0.8.2.gem`. It is likely that you need to grant write permissions for that path.


Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/racc-1.6.2.gem`. It is likely that you need to grant write permissions for that path.
Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/hashery-2.1.2.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ruby-rc4-0.1.5.gem`. It is likely that you need to grant write permissions for that path.

Fetching ttfunk 1.7.0



Using rainbow 3.1.1
Using zeitwerk 2.6.8
Using yell 2.2.2

Retrying download gem from https://rubygems.org/ due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ttfunk-1.7.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (3/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ttfunk-1.7.0.gem`. It is likely that you need to grant write permissions for that path.

Retrying download gem from https://rubygems.org/ due to error (4/4): Bundler::PermissionError There was an error while trying to write to `/usr/share/gems/cache/ttfunk-1.7.0.gem`. It is likely that you need to grant write permissions for that path.

Bundler::PermissionError: There was an error while trying
to write to `/usr/share/gems/cache/rake-13.0.6.gem`. It is
likely that you need to grant write permissions for that
path.
 
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/shared_helpers.rb:105:in
`rescue in filesystem_access'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/shared_helpers.rb:102:in
`filesystem_access'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:483:in
`block in download_gem'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/retry.rb:40:in
`run'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/retry.rb:30:in
`attempt'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/rubygems_integration.rb:474:in
`download_gem'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:481:in
`download_gem'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:443:in
`fetch_gem'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:427:in
`fetch_gem_if_possible'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:156:in
`install'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer/gem_installer.rb:54:in
`install'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:156:in
`do_install'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:84:in
`call'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:67:in
`call'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer.rb:244:in
`install_in_parallel'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer.rb:201:in
`install'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer.rb:89:in
`block in run'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/process_lock.rb:19:in
`rescue in lock'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/process_lock.rb:15:in
`lock'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer.rb:71:in
`run'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/installer.rb:23:in
`install'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/cli/install.rb:62:in
`run'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/cli.rb:261:in
`block in install'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/settings.rb:131:in
`temporary'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/cli.rb:260:in
`install'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in
`run'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in
`invoke_command'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in
`dispatch'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in
`dispatch'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in
`start'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in
`start'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/exe/bundle:45:in
`block in <top (required)>'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in
`with_friendly_errors'
/home/websnke/.local/share/gem/ruby/gems/bundler-2.4.12/exe/bundle:33:in
`<top (required)>'
  /home/websnke/bin/bundle:25:in `load'
  /home/websnke/bin/bundle:25:in `<main>'

An error occurred while installing rake (13.0.6),
and Bundler cannot continue.

In Gemfile:
  rake
```

I think that the instructions are missing a few steps and it would be great if the README could be more descriptive.

**Comment by SMillerDev** [comment]
> Bundler::PermissionError: There was an error while trying
to write to `/usr/share/gems/cache/rake-13.0.6.gem`. It is
likely that you need to grant write permissions for that
path.

This is not something the Rakefile controls so it seems there is just an issue with your machine.

**Comment by carlocab** [comment]
OTOH, the README should probably provide instructions to contributors that enable them to contribute without needing `sudo` to test their changes.

**Comment by MikeMcQuaid** [comment]
I agree that the README should be improved here.

**Comment by WebSnke** [comment]
@MikeMcQuaid 
Could you please write complete instructions to run brew.sh locally? I tried a few times now but it doesn't work.

**Comment by MikeMcQuaid** [comment]
@WebSnke Yes but it'll take me a little but to get there, sorry.

**Comment by kbdharun** [comment]
> @MikeMcQuaid Could you please write complete instructions to run brew.sh locally? I tried a few times now but it doesn't work.

Complete instructions are available now.
